### PR TITLE
fix: subscription calldata

### LINKED ISSUE #811: `Subscription` all currencies bug
I'm already subscribed with ETH, when I choose ETH and I click on the button nothing appears. We need to notify the user he is already subscribed to this currency. (we can do it on the button disable message)
Capture d’écran 2024-05-29 à 17 21 17

### PR DESCRIPTION
**Pull request by fricoben**
close #811 

## Summary by CodeRabbit

- **New Features**
	- Enhanced subscription logic to include additional checks for available domains, preventing the subscription button from being enabled without any domains.
	- Updated subscription button text to "You're already subscribed" when no domains are available, providing clearer user feedback.

### CODE REVIEW

File: components/domains/autorenewal.tsx [hunk 1]
```diff
@@ -398,7 +398,8 @@ const Subscription: FunctionComponent<SubscriptionProps> = ({ groups }) => {
                 !address ||
                 !termsBox ||
                 (needMedadata && emailError) ||
-                !areDomainSelected(selectedDomains)
+                !areDomainSelected(selectedDomains) ||
+                !(callData.length > 0) // Cover the case where there are no domains to subscribe
```
Comment (Marchand-Nicolas) [inline components/domains/autorenewal.tsx]: !(callData.length > 0) is the same as callData.length === 0. Isn't it cleaner that way ?

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]

File: components/domains/autorenewal.tsx (hunk 1 above)
Comment (fricoben) [reply components/domains/autorenewal.tsx]: agree

**Review by Marchand-Nicolas — APPROVED** [review]
lgtm
