### PR TITLE
fix: hiding address

### LINKED ISSUE #800: Virgin ID show an address when it shouldn't
Capture d’écran 2024-05-22 à 14 17 48

I shouldn't see any address here cause we're supposed to show the address of the domain. Which begs the question are we checking the right address (the target address and not the connected address).

### PR DESCRIPTION
**Pull request by Marchand-Nicolas**
close: #800 

## Summary by CodeRabbit

- **Bug Fixes**
  - Removed the `minifyAddress` function from the `IdentityCard` component, resulting in the full address being displayed in the UI instead of a shortened version.

### CODE REVIEW

File: components/identities/identityCard.tsx [hunk 1]
```diff
@@ -123,13 +121,6 @@ const IdentityCard: FunctionComponent<IdentityCardProps> = ({
               <div className="flex flex-col">
                 {identity?.targetAddress ? (
                   <>
-                    <div className={styles.addressBar}>
-                      <h2>{minifyAddress(identity.targetAddress)}</h2>
-                      <CopyContent
-                        value={identity?.targetAddress}
-                        className="cursor-pointer ml-3"
-                      />
-                    </div>
```
Comment (fricoben) [inline components/identities/identityCard.tsx:132]: Nope, here you delete the address for every identity. We want to delete the address for the virgin identities only. For the domains we want to keep them :)

**Review by fricoben — CHANGES_REQUESTED** [review]
misunderstanding

**Review by fricoben — APPROVED** [review]
lgtm
