### PR TITLE
Fix: Added a new card below Renew your domain when the subscription i…

### LINKED ISSUE #1092: New "subscription button" - Add new card when subscription is inactive
## Description 📹

Current :
Image

New design :
Image

Figma : https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=6875-20324&t=XCt8XQUo4vZRtmIv-1

**Add a new card below "Renew your domain" when the subscription is inactive. Only the background, not the content inside. We will add the content via other issues.Hide the "Change domain target" button with the other buttons under "View more."**

The purpose of this issue is to add a new "subscription button" card to the Starknet ID platform when the subscription is inactive.

### Issue Details
- **Current State**: The subscription button is not present when the subscription is inactive.
- **Proposed State**: Add a new card below "Renew your domain" when the subscription is inactive.
- **Design**: The new design is available on Figma (link provided in the issue description).

### Actions to Take
1. **Fork and Branch Creation**:
   - Fork the repository and create a new branch using the issue number.

2. **Implementation of Changes**:
   - Add the new card below "Renew your domain" when the subscription is inactive.
   - Implement only the background of the card, not the content inside.
   - Hide the "Change domain target" button with other buttons under "View more."

3. **Testing and Validation**:
   - Test modifications locally.
   - Verify that existing functionalities are not affected.

4. **Commit and Submission**:
   - Make a commit with a clear message describing the addition of the new card.
   - Submit a pull request closing the issue.

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed with a mardown todo list]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by snehaa-eth**
…s inactive
close #1092 

## Summary by CodeRabbit

- **New Features**
  - Added a new container for upcoming subscription content after the "RENEW YOUR DOMAIN" action for eligible domains.

- **Refactor**
  - The "CHANGE DOMAIN TARGET" action visibility and placement now adjust dynamically based on domain type and auto-renewal status, enhancing user interaction flow.
  - Improved auto-renewal status tracking per domain, ensuring accurate display of renewal options and subscription information.

### CODE REVIEW

**Comment by snehaa-eth** [comment]
@Marchand-Nicolas pls check pr

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Should only be displayed if
callDataEncodedDomain?.[0] === "1" && !isAutoRenewalEnabled 

To ensure that the domain is not a subdomain, and that the subscription is disabled

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
image
There is no button anymore displayed when visiting a subdomain (https://app-starknet-75c4zhnl8-lfglabs.vercel.app/identities/251088324202) by default.

So I think you should only put the button inside the "view more" category if the new card is displayed. If the new card is not displayed (not a main domain, or subscription active) then you should display the 'CHANGE DOMAIN TARGET" as it was before.

The rest is perfect, well done!

**Comment by snehaa-eth** [comment]
on sepolia this identity is not there...can you give me one example on sepolia ?so i can verify

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
If I select an identity for which the subscription is active, I don't see the card (so as expected). But then if I navigate to and identity for which the subscription is inactive, I don't see it neither. When I reload the page it appears

File: components/identities/actions/identityActions.tsx [hunk 1]
```diff
@@ -269,21 +271,47 @@ const IdentityActions: FunctionComponent<IdentityActionsProps> = ({
                       onClick={() => router.push("/renewal")}
                     />
                   ) : null}
+                  
+             
+                  {showChangeTargetButtonByDefault && !viewMoreClicked && (
```
Comment (Marchand-Nicolas) [inline components/identities/actions/identityActions.tsx]: Here it should be only showChangeTargetButtonByDefault I think

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]

**Review by Marchand-Nicolas — APPROVED** [review]
Great job! Just made a small fix, LGTM

**Comment by snehaa-eth** [comment]
oh yeah i also made and pushed
