### PR TITLE
Fix #924 - some expiring domains not showing as expired

### LINKED ISSUE #924: On `/identities` I have expired domains that don't seem expired
## Description 📹

On `/identities` I have expired domains that don't seem expired, when I click on them I can see clearly they are 👇

Capture d’écran 2024-11-25 à 11 18 35

We need to add a warning label in red as we do with the `subscription` when a domain is expired to inform the user directly on `/identity`

## Proposed Actions 🛠️

Here's a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
   - [ ] Update the warning condition in IdentitiesGalleryV1 component:
   ```typescript:components/identities/identitiesGalleryV1.tsx
   // ... existing code ...
   {needAutoRenewal?.includes(identity.domain) && 
    (isIdentityExpired(identity) || isIdentityExpiringSoon(identity)) ? (
     <div className={styles.expiryWarning}>
       <Tooltip
         title={
           isIdentityExpired(identity)
             ? "This domain has expired! Renew it now to keep using it."
             : `This domain will expire on ${timestampToReadableDate(identity?.domain_expiry ?? 0)}`
         }
         arrow
       >
         <RebewalIcon color={isIdentityExpired(identity) ? "error" : "warning"} />
       </Tooltip>
     </div>
   ) : null}
   // ... existing code ...
   ```

This code exists right now but it doesn't work so please find out why (timestamp conversion problem or something else), moreover transform the warning (yellow) color in error (red) if it's expired).

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: Add distinct warning for expired domains"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren't assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by emarc99**
Close #924 

## Summary by CodeRabbit

- **New Features**
	- Enhanced wallet connection logic for the Argent mobile app.
	- Improved expiration status display for identities in the gallery.

- **Bug Fixes**
	- Updated tooltip messages for expired and expiring domains in the identities gallery.

- **Chores**
	- Added `.env` to the `.gitignore` file for better version control practices.
	- Reformatted licensing text for improved readability.

### CODE REVIEW

**Comment by fricoben** [comment]
wen ready ? @emarc99

**Comment by emarc99** [comment]
I am still working on it, trying to detect where errors occur by passing statically-generated domain_expiry values in precise format as the response from api.starknet.id and using relevant functions within the project.

Will make a PR soon, please.

> wen ready ? @emarc99

**Comment by fricoben** [comment]
> I am still working on it, trying to detect where errors occur by passing statically-generated domain_expiry values in precise format as the response from api.starknet.id and using relevant functions within the project.

need to finish asap for OD hack

File: components/identities/identitiesGalleryV1.tsx [hunk 1]
```diff
@@ -64,19 +64,20 @@ const IdentitiesGalleryV1: FunctionComponent<IdentitiesGalleryV1Props> = ({
...
+                      ? "This domain has expired! Renew it now to keep using it."
+                      : `This domain will expire on ${timestampToReadableDate(
                           identity?.domain_expiry ?? 0
                         )}`
                   }
                   arrow
                 >
-                  <ErrorIcon color="error" />
+                  {/* <ErrorIcon color="error" /> */}
+                  <RenewalIcon color={isIdentityExpired(identity) ? "#FF3333" : "#FFDE21"} width="12" />
```
Comment (Marchand-Nicolas) [inline components/identities/identitiesGalleryV1.tsx]: Why are you changing the icon ? Also the hover tooltip doesn't work for me on your PR

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Doesn't work for me.
The aim of the issue is just to show the red warning icon on every expired domain. Where currently there are some domains that show as expired, and other that doesn't, even though they are expired. You can check on my screenshot, the "TESTET.STARK" domain should show as expired.
You can try to mock with my address if it can help you: 0x05F1F8De723d8117daA26ec24320d0EacabC53a3D642Acb0880846486e73283a
Screenshot 2024-12-05 at 11 44 36 PM

File: components/identities/identitiesGalleryV1.tsx (hunk 1 above)
Comment (emarc99) [reply components/identities/identitiesGalleryV1.tsx]: Ok, I'll make sure the requested changes are applied, and try the mock address, thanks.

Comment (emarc99) [reply components/identities/identitiesGalleryV1.tsx]: `curl https://api.starknet.id/renewal/get_non_subscribed_domains?addr=0x05F1F8De723d8117daA26ec24320d0EacabC53a3D642Acb0880846486e73283a`
gives below result 
["testapple.stark","sdfsdqdsd.stark","testniin.stark","qzdqsddqz.stark","test5.stark","niko.stark","dsqqsdsqds.stark","testnico.stark","testnicooo.stark"]

Comment (Marchand-Nicolas) [reply components/identities/identitiesGalleryV1.tsx]: > `curl https://api.starknet.id/renewal/get_non_subscribed_domains?addr=0x05F1F8De723d8117daA26ec24320d0EacabC53a3D642Acb0880846486e73283a` gives below result ["testapple.stark","sdfsdqdsd.stark","testniin.stark","qzdqsddqz.stark","test5.stark","niko.stark","dsqqsdsqds.stark","testnico.stark","testnicooo.stark"]

Yes, because it returns the domains that are not subscribed to auto renewal.

Comment (emarc99) [reply components/identities/identitiesGalleryV1.tsx]: Obviously, the ones from response have the red icon from the image you shared. "TESTET.STARK" is missing.

Comment (emarc99) [reply components/identities/identitiesGalleryV1.tsx]: After studying [api.starknet.id](https://github.com/lfglabs-dev/api.starknet.id/tree/testnet)/[src](https://github.com/lfglabs-dev/api.starknet.id/tree/testnet/src)/[endpoints](https://github.com/lfglabs-dev/api.starknet.id/tree/testnet/src/endpoints)/[renewal](https://github.com/lfglabs-dev/api.starknet.id/tree/testnet/src/endpoints/renewal)
/get_non_subscribed_domains.rs
The renewal/get_non_subscribed_domains response, filters out some expired domains based on their renewal status. This means even though they are expired, they are not considered "non-subscribed"

Comment (emarc99) [reply components/identities/identitiesGalleryV1.tsx]: > > `curl https://api.starknet.id/renewal/get_non_subscribed_domains?addr=0x05F1F8De723d8117daA26ec24320d0EacabC53a3D642Acb0880846486e73283a` gives below result ["testapple.stark","sdfsdqdsd.stark","testniin.stark","qzdqsddqz.stark","test5.stark","niko.stark","dsqqsdsqds.stark","testnico.stark","testnicooo.stark"]
> 
> Yes, because it returns the domains that are not subscribed to auto renewal.

So, can I change this to get all domains, then filter to get expired ones for showing red for `expired` and yellow for `expiring soon`?
Basically, I am asking if I can use another api edpoint apart from `/renewal/get_non_subscribed_domains?` to achieve my task? I am thinking of using `/addr_to_full_ids?addr=` for expired/expiring soon and `/renewal/get_non_subscribed_domains?`  for renew subscription indicator.

Comment (Marchand-Nicolas) [reply components/identities/identitiesGalleryV1.tsx]: > Obviously, the ones from response have the red icon from the image you shared. "TESTET.STARK" is missing.

No, e.g.: niko.stark is not expired but is returned by this route as I disabled the autorenewal for it
image

Please don't use this route, it has nothing to do with the issue

Comment (Marchand-Nicolas) [reply components/identities/identitiesGalleryV1.tsx]: > After studying [api.starknet.id](https://github.com/lfglabs-dev/api.starknet.id/tree/testnet)/[src](https://github.com/lfglabs-dev/api.starknet.id/tree/testnet/src)/[endpoints](https://github.com/lfglabs-dev/api.starknet.id/tree/testnet/src/endpoints)/[renewal](https://github.com/lfglabs-dev/api.starknet.id/tree/testnet/src/endpoints/renewal) /get_non_subscribed_domains.rs The renewal/get_non_subscribed_domains response, filters out some expired domains based on their renewal status. This means even though they are expired, they are not considered "non-subscribed"

Yes but that's not what we want

Comment (Marchand-Nicolas) [reply components/identities/identitiesGalleryV1.tsx]: Just use the expiry of each domain to determine if it's expired, and then show the red icon to tell the user it's expired

Comment (emarc99) [reply components/identities/identitiesGalleryV1.tsx]: Awesome, thanks!

**Comment by emarc99** [comment]
@Marchand-Nicolas please help test. I tested by mocking your public address.
image

File: components/identities/identitiesGalleryV1.tsx [hunk 2]
```diff
@@ -57,28 +57,28 @@ const IdentitiesGalleryV1: FunctionComponent<IdentitiesGalleryV1Props> = ({
...
-                          identity?.domain_expiry ?? 0
-                        )}`
-                  }
-                  arrow
-                >
+                <Tooltip title="This domain has expired! Renew it now to keep using it." arrow>
                   <ErrorIcon color="error" />
                 </Tooltip>
               </div>
+            ) : isExpiringSoon ? (
```
Comment (Marchand-Nicolas) [inline components/identities/identitiesGalleryV1.tsx]: Here it should be isExpiringSoon && needAutoRenewal?.includes(identity.domain)

Because we don't want to tell the user it'll expire soon if they enabled auto renewal (as it'll be renewed automatically)

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]

**Review by Marchand-Nicolas — APPROVED** [review]
Lgtm!
