### PR TITLE
fix : Enable Subscription Form - Edit input size of ETH OR STRK

### LINKED ISSUE #1107: Enable Subscription Form - Edit input size of ETH OR STRK
## Description 📹

Current :
Image

New design :
Image

Figma : https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=6875-20324&t=XCt8XQUo4vZRtmIv-1

**Edit input size of ETH OR STRK**

The purpose of this issue is to modify the input size for ETH OR STRK in the Enable Subscription Form on the Starknet ID platform. Here are the details:

### Purpose of the Issue
Edit the input size for ETH OR STRK in the Enable Subscription Form to match the new design provided in Figma.

### Issue Details
- **Current State**: The input size does not match the new design specifications.
- **Proposed State**: The input size should be adjusted according to the Figma design.
- **Design**: The new design is available on Figma (link provided in the issue description).

### Actions to Take
1. **Fork and Branch Creation**:
   - Fork the repository and create a new branch using the issue number.

2. **Implementation of Changes**:
   - Adjust the input size for ETH OR STRK in the Enable Subscription Form to match the Figma design.
   - Ensure the changes integrate properly with other components.

3. **Testing and Validation**:
   - Test modifications locally.
   - Verify that existing functionalities are not affected.

4. **Commit and Submission**:
   - Make a commit with a clear message describing the input size adjustment.
   - Submit a pull request closing the issue.

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed with a mardown todo list]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by pheobeayo**
fix the input size of the ETH OR STRK of the subscription form
Closes #1107 

## Summary by CodeRabbit

- **New Features**
  - The currency dropdown now presents a refreshed display of the selected option, featuring an accompanying icon and improved formatting for clearer visual feedback.
  - Added a custom rendering function for the selected currency value, enhancing the user experience.
  - Introduced an arrow icon to improve the visual representation of the dropdown.

- **Style**
  - Layout adjustments ensure that the currency switcher spans the full width of its container, resulting in a more refined and balanced interface.
  - Enhanced styling for the dropdown component, including updated padding and visibility of the default icon.

### CODE REVIEW

**Comment by pheobeayo** [comment]
@Marchand-Nicolas Kindly review please

File: components/domains/arCurrencyDropdown.tsx [hunk 1]
```diff
@@ -1,3 +1,16 @@
+/**
```
Comment (wheval) [inline components/domains/arCurrencyDropdown.tsx]: Remove this

**Review by wheval — CHANGES_REQUESTED** [review]
Screenshot 2025-03-28 041755
use the correct icon for the select

File: components/domains/arCurrencyDropdown.tsx (hunk 1 above)
Comment (pheobeayo) [reply components/domains/arCurrencyDropdown.tsx]: okay

**Comment by Marchand-Nicolas** [comment]
@wheval thank you so much for you review

**Review by Marchand-Nicolas — APPROVED** [review]
It looks so good and the code is very clean, LGTM :D
