### PR TITLE
fix: show displayed currency in registerCheckboxes hint subscription msg

### LINKED ISSUE #737: Explaination mentioning ETH when STRK is set
Capture d’écran 2024-04-22 à 18 45 58

### PR DESCRIPTION
**Pull request by irisdv**
Close #737

### CODE REVIEW

File: components/domains/registerCheckboxes.tsx [hunk 1]
```diff
@@ -71,8 +75,12 @@ const RegisterCheckboxes: FunctionComponent<RegisterCheckboxes> = ({
...
-            helperText={`Enabling a subscription permits Starknet ID to renew your domain automatically every year for you! This approval gives us only the possibility to renew your domain once per year maximum ${
-              ethRenewalPrice ? `(${gweiToEth(ethRenewalPrice)} ETH/year)` : ""
+            helperText={`Enabling a subscription permits Starknet ID to renew your domain automatically every year for you! This approval gives us only the possibility to renew your domain once per year ${
+              maxPriceRange
+                ? `(maximum ${Number(gweiToEth(maxPriceRange)).toFixed(
+                    3
+                  )} ${displayedCurrency}/year)`
+                : ""
             } and we'll cover the transaction fee for you!`}
           >
```
Comment (fricoben) [inline components/domains/registerCheckboxes.tsx]: Seems a bit long and difficult to put inline. 

Could you create a `const` ?

**Review by fricoben — CHANGES_REQUESTED** [review]
Some minor improvement and we're good !

**Review by fricoben — APPROVED** [review]
lgtm
