### PR TITLE
fix: impossible to click on View Less

### LINKED ISSUE #508: Impossible to click on `View Less`
Capture d’écran 2023-11-22 à 16 04 00

Impossible to click on `View Less` because the feedback is before it. For this feedbacks and also the others we should add the possibility to close them like so.

Capture d’écran 2023-11-28 à 17 43 58

Ressources
https://mui.com/material-ui/react-snackbar/
https://mui.com/material-ui/react-alert/

### PR DESCRIPTION
**Pull request by Marchand-Nicolas**
close: #508

### CODE REVIEW

File: components/identities/identityWarnings.tsx [hunk 1]
```diff
@@ -13,6 +13,7 @@ const IdentityWarnings: FunctionComponent<IdentityWarningsProps> = ({
   identity,
   isIdentityADomain,
 }) => {
+  const [hideExpiredNotification, setHideExpiredNotification] = useState(false);
```
Comment (fricoben) [inline components/identities/identityWarnings.tsx]: `closeNotification` is an easier wording imo !

**Review by fricoben — CHANGES_REQUESTED** [review]
Cool! Just some wording to change :)

**Review by fricoben — APPROVED** [review]
lgtm
