### PR TITLE
Fix: Added No NFTs FOUND state in your NFTs category

### LINKED ISSUE #972: "No NFTS FOUND" state in your NFTs category
## Description 📹

Current one : 
image

New design :
Screenshot 2025-01-06 at 14 37 01

Figma file : https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=4206-23330&t=voihEFkmKVAooepr-1

**By clicking on 'edit' of their stark profile picture and if the user has no NFT in their wallet, this page should be displayed. So, we follow the same structure as the NFT categories redesign but with a title and a description. So add title and description**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed with a mardown todo list]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by Koda-Black**
close: #972

## Summary by CodeRabbit

- **New Features**
	- Enhanced the profile picture selection experience by displaying context-sensitive messages. Users now see a prompt encouraging them to acquire NFTs when none are available, and navigation elements are shown only when NFTs exist.

- **Style**
	- Introduced updated visual styling for empty NFT states to improve layout and readability, including adjustments to font size and responsive design elements. A new CSS class has been added for better responsiveness, along with modifications to existing styles for consistency.

### CODE REVIEW

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
The title size should be 36px

Too much padding on mobile

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
image
You removed the padding from all containers (when there are pfps).

Please test your code and make sure everything works and that you didn't break anything before pushing, because the reward is reduced for every review. Autonomy is valued.

**Comment by Koda-Black** [comment]
These reviews have been implemented on all screens. Thank you for your patience.
Screenshot 2025-02-16 133136
Screenshot 2025-02-16 125725
Screenshot 2025-02-16 125608
Screenshot 2025-02-16 125656

File: components/identities/pfpGallery.tsx [hunk 1]
```diff
@@ -51,10 +52,11 @@ const PfpGallery: FunctionComponent<PfpGalleryProps> = ({
             })
           ) : (
             <div className="flex flex-col align-middle items-center">
-              <img src="/visuals/notFound.webp" alt="Not found" width={201} />
-              <WarningMessage>
-                You don&apos;t own any whitelisted NFTs yet
-              </WarningMessage>
+              <h2 className={styles.title}>NO NFTS FOUND</h2>
+              <p className={styles.subtitle}>
+                You don’t own any whitelisted NFTs yet. Get your first NFT to
```
Comment (Marchand-Nicolas) [inline components/identities/pfpGallery.tsx]: Use `&apos;` instead of the ' char

File: components/identities/updateProfilePic.tsx [hunk 2]
```diff
@@ -40,25 +40,32 @@ const UpdateProfilePic: FunctionComponent<UpdateProfilePicProps> = ({
...
+  const hasNoNfts = userNfts.length === 0;
+
   return (
     <>
       <div className={styles.container}>
-        <div className={styles.arrows}>
-          <BackButton onClick={() => back()} />
-        </div>
-        <div className={styles.gallery}>
+        {!hasNoNfts && (
```
Comment (Marchand-Nicolas) [inline components/identities/updateProfilePic.tsx]: Can you completly remove the back button please. It's not there anymore on the new design

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Two changes and we're good

File: components/identities/updateProfilePic.tsx (hunk 2 above)
Comment (Koda-Black) [reply components/identities/updateProfilePic.tsx]: Done

File: components/identities/pfpGallery.tsx (hunk 1 above)
Comment (Koda-Black) [reply components/identities/pfpGallery.tsx]: Done

**Review by Marchand-Nicolas — APPROVED** [review]
Good lgtm!

**Review by Divineifed1 — COMMENTED** [review]
The padding for the NO NFTs FOUND container for the mobile view has bee 
n adjusted properly
