### PR TITLE
fix: identity after registration

### LINKED ISSUE #860: Go to your identity after registration skeleton
This video shows the feedback after the registration from the UI is strange when I click on `go to your domain`. The tx is taking long time so that's the issue that sould be fixed soon by Starknet itself, but our way of showing the loading with skeleton makes me think of a bug so I would prefer to make the skeleton better (not only the PFP loadding but all the part of the card with their associated skeleton too and maybe a message with it).

https://www.loom.com/share/c034501fb976404ea9d9794774b0611b

### PR DESCRIPTION
**Pull request by Marchand-Nicolas**
close: #860 

## Summary by CodeRabbit

- **New Features**
	- Enhanced the IdentityCard component to provide real-time feedback during the identity minting process.
	- Introduced improved data fetching and rendering logic in the TokenIdPage component, adapting to the minting state based on URL parameters.

- **Style**
	- Renamed `identityActionsSkeleton` to `IdentityActionsSkeleton` to adhere to React naming conventions, improving clarity.

### CODE REVIEW

File: pages/identities/[tokenId].tsx [hunk 1]
```diff
@@ -114,14 +133,16 @@ const TokenIdPage: NextPage = () => {
...
+                  {!hideActions ? (
                     <IdentityActions
                       isOwner={isOwner}
                       tokenId={tokenId}
                       isIdentityADomain={isIdentityADomain}
                       identity={identity}
                       hideActionsHandler={hideActionsHandler}
                     />
+                  ) : (
+                    minting && <IdentityActionsSkeleton />
```
Comment (fricoben) [inline pages/identities/[tokenId].tsx:158]: Comme dis dans la video il doit y avoir un problème dans ce code car j'ai eu ça 

Capture d’écran 2024-07-22 à 17 29 16

**Review by fricoben — CHANGES_REQUESTED** [review]
## E2E 

Code seems ok but I have a problem here:

https://loom.com/share/47c77b0e488b49f799a76d679763143f

File: components/identities/identityCard.tsx [hunk 2]
```diff
@@ -101,6 +104,14 @@ const IdentityCard: FunctionComponent<IdentityCardProps> = ({
               </Tooltip>
             ) : null}
           </div>
+          {minting ? (
+            <div className="text-left h-full py-2">
+              <h1 className="text-3xl font-bold">Minting your identity...</h1>
```
Comment (fricoben) [inline components/identities/identityCard.tsx]: use the H1 font QuickZap here

**Review by fricoben — APPROVED** [review]
lgtm
