### PR TITLE
Fix column categories for profile picture categories

### LINKED ISSUE #968: Add column categories for profile picture categories
## Description 📹

Current one : 
image
image

New design :
Screenshot 2024-12-31 at 16 24 11
Screenshot 2024-12-31 at 16 24 30
Screenshot 2024-12-31 at 16 24 49

Figma file : https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=4181-26462&t=2s8rQG6hx1hS6Ob1-1

**Currently, when trying to modify the profile picture, everything is mixed together and we have to scroll to see all the categories. We need to display everything on a single page without scrolling. To achieve this, a left column should be added (the same one used for purchasing a domain) to separate the categories. The categories should be: first, 'Your NFTs'; second, 'Starknet ID Ecosystem' (which is also available on the PFP collections page: https://app.starknet.id/pfpcollections); and third, 'Overall Starknet Ecosystem'**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed with a mardown todo list]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by Gladchux14**
FIX: COLUMN FOR EDIT NFT PICTURE CATEGORIES

DESCRIPTION:
Improved the edit NFT picture page to include categories which enables toggling between sections and the sections are viewed once on the page instead of scrolling to get to each of the sections:  

CLOSES #968 

###What I did:
- create a sidebar for the edit NFT
- add two more sections (starknet id system and overall starkenet Ecosystem) from the pfp collection.
- implement the page so it can toggle for the sections.
- made the page responsive.

###Changes:
- add icons for the category section tittle.
- add image for the sidebar .

###Images:
sep01

sepo02

## Summary by CodeRabbit

- **New Features**
  - Revamped the profile picture update experience with a multi-step navigation sidebar.
  - Introduced three tabs allowing users to explore different NFT collections: "Your NFTs", "Starknet ID Ecosystem", and "Overall Starknet Ecosystem".
  - Streamlined the interface to provide an intuitive selection process while maintaining a consistent layout for profile picture updates.

### CODE REVIEW

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
image
This is completely broken.
Your issue was only about the left bar, please focus on that.
You should have simply reused the component we use in https://app.starknet.id/register/testt.stark
Your new component doesn't look like on figma. Please reuse the existing one and make it more modular.

**Comment by Gladchux14** [comment]
alright, will make changes and revert.

**Comment by Marchand-Nicolas** [comment]
@Gladchux14 please read the comments made by the AI. It is right. https://github.com/lfglabs-dev/app.starknet.id/pull/1060#discussion_r1960525922

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Currently, you display both first and last step in the first step
image
Please display
Screenshot 2025-02-19 at 10 36 49 AM
on the first step

And
image
on the last step.

Screenshot 2025-02-19 at 10 37 25 AM
Also, the navbar is too close to the edges.
It should look a bit like https://sepolia.app.starknet.id/renewal

Also, here it's not the right icon:
image

Finally, I see you broke a bit the nav component on other pages:
image
Please fix that so that it looks exactly like on https://sepolia.app.starknet.id/renewal

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Doesn't build.
Make sure you test your code, because OD automatically reduces your reward every time I have to review again

**Comment by Marchand-Nicolas** [comment]
Also, check the comments made by the AI

**Review by Divineifed1 — APPROVED** [review]
looks great but it l don't think its builds, try to confirm your code before  creating a PR

File: components/UI/Sidebar.tsx [hunk 1]
```diff
@@ -0,0 +1,78 @@
+import React from 'react';
```
Comment (Marchand-Nicolas) [inline components/UI/Sidebar.tsx]: Don't create a new sidebar component.
Please reuse the one we already developped components/domains/steps/registerSteps.tsx.
You'll just need to add new props to make it reusable

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
image

This component is broken. Please cancel the changes you made on it so that it looks like on https://sepolia.app.starknet.id/

Also, there is code to clean, I make a comment for that. You must reuse code as much as possible, instead of rewriting it

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
It doesn't build

**Comment by Marchand-Nicolas** [comment]
It has been two weeks @Gladchux14 do you mind if I assign someone else ?

File: components/domains/registerV3.tsx [hunk 2]
```diff
@@ -52,31 +56,42 @@ const RegisterV3: FunctionComponent<RegisterV3Props> = ({ domain }) => {
...
         </aside>
 
         <div className={`${styles.purchaseStepNavMobile}`} role="navigation">
-          <RegisterSteps
+        <RegisterSteps
+            steps={stepsData}
             currentStep={currentStep}
             setStep={goToStep}
-            showPfp={userNfts && userNfts.length > 0}
+            showPfp={false}
```
Comment (Marchand-Nicolas) [inline components/domains/registerV3.tsx]: It should still be `userNfts && userNfts.length > 0`, not false

File: components/domains/steps/registerSteps.tsx [hunk 3]
```diff
@@ -1,120 +1,135 @@
...
 
-const RegisterSteps: FunctionComponent<registerStepsProps> = ({
+const RegisterSteps: React.FC<StepsProps> = ({
+  steps,
   currentStep,
   setStep,
-  showPfp = true,
   isLoading = false,
+  isSidebar = false,
+  showPfp = true,
```
Comment (Marchand-Nicolas) [inline components/domains/steps/registerSteps.tsx]: Should be false by default

File: components/UI/Sidebar.tsx [hunk 4]
```diff
@@ -0,0 +1,78 @@
...
+
+type SidebarProps = {
+  items: SidebarItem[];
+  activeId: string;
+  className?: string;
+};
+
+const getColor = (isActive: boolean) => isActive ? 'black' : 'gray'; // Function to determine color based on active state
+
+const Sidebar: React.FC<SidebarProps> = ({ items,  activeId }) => {
```
Comment (Marchand-Nicolas) [inline components/UI/Sidebar.tsx]: This component is not used, you can remove it

File: components/identities/updateProfilePic.tsx [hunk 5]
```diff
@@ -39,25 +47,97 @@ const UpdateProfilePic: FunctionComponent<UpdateProfilePicProps> = ({
...
+          role="navigation"
+        >
+          <RegisterSteps
+            steps={stepsData}
+            currentStep={currentStep}
+            setStep={goToStep}
+            showPfp={false}
             isLoading={isLoading}
-            title="Our Suggestions"
+            isSidebar={true}
```
Comment (Marchand-Nicolas) [inline components/identities/updateProfilePic.tsx]: Can you explain me the purpose of `isSidebar` please ?

File: components/identities/updateProfilePic.tsx [hunk 6]
```diff
@@ -39,25 +47,97 @@ const UpdateProfilePic: FunctionComponent<UpdateProfilePicProps> = ({
...
+              alt="Domain purchase steps visualization"
+            />
+          </div>
         </div>
-        {!hasNoNfts && (
-          <div className={styles.gallery}>
-            <SelectedCollections />
+
+        <div className={`flex-1 border-solid max-h-[calc(100vh-30rem)] lg:max-h-[calc(100vh-20rem)] h-full w-full overflow-y-auto ${styles["scrollbar-thin"]} p-6`}>
+          <div className={``}>
```
Comment (Marchand-Nicolas) [inline components/identities/updateProfilePic.tsx]: No empty classname

File: components/domains/registerV3.tsx [hunk 7]
```diff
@@ -52,31 +56,42 @@ const RegisterV3: FunctionComponent<RegisterV3Props> = ({ domain }) => {
...
     <>
       <div className="w-full flex flex-col xl:flex-row justify-center gap-4 px-3 py-4 lg:px-32 md:px-16 sm:py-12 xl:h-[88vh]">
         <aside className={`${styles.purchaseStepNav}`} role="navigation">
-          <RegisterSteps
+        <RegisterSteps
+            steps={stepsData}
             currentStep={currentStep}
             setStep={goToStep}
-            showPfp={userNfts && userNfts.length > 0}
+            showPfp={false}
```
Comment (Marchand-Nicolas) [inline components/domains/registerV3.tsx]: It should be `userNfts && userNfts.length > 0` instead of false

File: components/domains/renewalV2.tsx [hunk 8]
```diff
@@ -1,3 +1,4 @@
+
```
Comment (Marchand-Nicolas) [inline components/domains/renewalV2.tsx]: Remove this empty space

File: components/domains/registerV3.tsx [hunk 9]
```diff
@@ -1,3 +1,4 @@
+
```
Comment (Marchand-Nicolas) [inline components/domains/registerV3.tsx]: Remove this empty space

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
I'm really happy because now it's much better! Well done :)
Let's continue like that!
There is no hurry, so take the time to read your code (you can easily compare the changes you pushed here https://github.com/lfglabs-dev/app.starknet.id/pull/1060/files)
that way, it'll be cleaner!

Overall it looks great, but you changed the style of the sidebar (on all pages). We want to keep it as before:

With your PR:
image

(the main difference here is the spacing: margins and paddings)

image

(here, on mobile, you still display the elements as a list, even though it should be horizontal

Before: 
image

image


Please compare your changes with the original (using this link: https://github.com/lfglabs-dev/app.starknet.id/pull/1060/files) so that you cancel the changes that affect the style

File: components/identities/updateProfilePic.tsx (hunk 5 above)
Comment (Gladchux14) [reply components/identities/updateProfilePic.tsx]: the original `registerSteps` called in the `renewalV2.tsx` and `registerV3.tsx` are process which needs a particular element to be done with before you can move on to the next , which is not required in the `updateProfilePage.tsx` that the elements are for toggling between sections.
secondly, there are color(red & green) differences for when an action has been taken/done which is not required in the `updateProfilepage` that is for grey when inactive and black when active.
hence, the need to create the `isSideBar` props to make the registerSteps component modular for any type of page they are to be called in whether as a process or for toggling between sections.

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
There are still changes on the way the component look (font size, margins, and responsive). Please cancel all the changes that may affect its look. Please compare your local version to the one on https://sepolia.app.starknet.id/register/dsfdfs.stark instead of requesting a review everytime. Please check https://github.com/lfglabs-dev/app.starknet.id/pull/1060/files too.

Component in your PR:
image

image


Former component:
image

**Review by Marchand-Nicolas — APPROVED** [review]
Great lgtm! Code looks clean :)

**Review by Divineifed1 — COMMENTED** [review]
looking good and perfect
