### PR TITLE
fix: paymaster

### LINKED ISSUE #905: Don't use the free coupon is network is not the good one
Capture d’écran 2024-11-05 à 11 12 50

### LINKED ISSUE #906: Paymaster impossible to use in prod
This comes from the conversation we have with FLEX on telegram

telegram-cloud-photo-size-5-6147763059205193448-y

### PR DESCRIPTION
**Pull request by Marchand-Nicolas**
close: #905
close: #906 

## Summary by CodeRabbit

- **New Features**
	- Integrated typed data signing for a more streamlined signature process.
	- Added a new hook to manage network validation, enhancing user feedback for network status.
	- Improved loading state management for coupon processing based on network conditions.

- **Bug Fixes**
	- Improved error handling and logging for signing and transaction execution.
	- Adjusted TypeScript error handling in multiple components for better stability.
	- Enhanced connection management logic in the navbar for improved reliability.

- **Chores**
	- Updated dependencies to the latest compatible versions for improved performance and security.

### CODE REVIEW

File: components/UI/connectButton.tsx [hunk 1]
```diff
@@ -20,7 +20,9 @@ const ConnectButton: FunctionComponent = () => {
   }, [isConnected]);
 
   const connectWallet = async (connector: Connector) => {
-    await connectAsync({ connector });
+    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
+    // @ts-ignore
+    await connectAsync({ connector: connector });
```
Comment (fricoben) [inline components/UI/connectButton.tsx:25]: really needed ?

File: components/UI/navbar.tsx [hunk 2]
```diff
@@ -72,6 +71,8 @@ const Navbar: FunctionComponent = () => {
 
   const connectWallet = async (connector: Connector) => {
     try {
+      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
+      // @ts-ignore
```
Comment (fricoben) [inline components/UI/navbar.tsx:75]: why do you add that everywher e?

**Review by fricoben — CHANGES_REQUESTED** [review]
tested with braavos works well but with argent I have this on mainnet 
Capture d’écran 2024-11-10 à 17 57 17

+ some questions

File: components/UI/connectButton.tsx (hunk 1 above)
Comment (Marchand-Nicolas) [reply components/UI/connectButton.tsx:25]: Yes it doesn't build because of a linter error

Comment (Marchand-Nicolas) [reply components/UI/connectButton.tsx:25]: I think we updated our configuration/linter on Vercel, because these errors where already there, and should have in theory blocked any PR from being deployed

**Comment by Marchand-Nicolas** [comment]
> tested with braavos works well but with argent I have this on mainnet Capture d’écran 2024-11-10 à 17 57 17

Yes there is an issue with Argent currently. The AVNU team is in company retreat in Thailande, so I'm waiting for them to fix the error encountered. For now, I replaced paymaster by a traditional tx for argent, isn't it working ?

File: components/UI/connectButton.tsx (hunk 1 above)
Comment (Marchand-Nicolas) [reply components/UI/connectButton.tsx:25]: The latest versions of starknet react and starknetkit have incompatible types, but work well (as it used to do) in practice. We can either wait for the next update, or I can also ask Cecco if there is anything to fix this type issue.

**Review by fricoben — APPROVED** [review]
lgtm
