### PR TITLE
fix: domain navigation

### LINKED ISSUE #944: New Domain navigation/ Add left column
## Description 📹

Current one : https://app.starknet.id/identities
image

https://app.starknet.id/identities/855076439471
image

New design :
image

Figma file : https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=4108-40951&t=wEy6O4uIMpUixad7-1

**Add a left column with all available domain wallets for the user. When a domain is clicked, the card view changes to display the selected domain. The user can add identities using the button at the bottom. Currently, we have two pages: one for selecting a domain and another for viewing the domain details. The goal is to simplify navigation and centralize everything on a single page.**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed with a mardown todo list]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by blessingbytes**
close #944

## Summary by CodeRabbit

- **New Features**
  - Introduced a new component for displaying available identities.
  - Enhanced functionality for managing user identities, including fetching and displaying profile pictures.
  
- **Improvements**
  - Streamlined the user interface by prioritizing the display of available identities.
  - Simplified the rendering logic for identity management, reducing complexity.

### CODE REVIEW

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Well done, it looks good and it works well! There are a few changes to do
In the list, show the domain if available instead of the id
Screenshot 2025-01-27 at 10 01 45 AM

Instead of showing the identity list in https://app-starknet-g48puevic-lfglabs.vercel.app/identities you should show your new menu, with the first identity selected by default
Screenshot 2025-01-27 at 10 03 46 AM

On figma the shadow is not the same, and you forgot the small border

image

There is more padding on figma
image

**Comment by blessingbytes** [comment]
@Marchand-Nicolas,  please how can i get the domain name for each mint domain, currently am able to get only the id of the mint domain,
Is there a specific function or a doc i can use to get the domain name

**Comment by Marchand-Nicolas** [comment]
> @Marchand-Nicolas, please how can i get the domain name for each mint domain, currently am able to get only the id of the mint domain, Is there a specific function or a doc i can use to get the domain name

Hello, I answered on telegram :)

File: pages/identities.tsx [hunk 1]
```diff
@@ -95,6 +95,12 @@ const Identities: NextPage = () => {
     execute();
   }
 
+  useEffect(()=>{
```
Comment (Marchand-Nicolas) [inline pages/identities.tsx]: Instead of redirecting the user, wrap your code from `pages/identities/[tokenId].tsx` in a component you can reuse in both files

File: pages/identities/[tokenId].tsx [hunk 2]
```diff
@@ -16,6 +20,11 @@ import { formatHexString } from "../../utils/stringService";
 import { getDomainData } from "@/utils/cacheDomainData";
 import { useSearchParams } from "next/navigation";
 import IdentityActionsSkeleton from "@/components/identities/skeletons/identityActionsSkeleton";
+import { hexToDecimal } from "@/utils/feltService";
+import AddButton from "@/components/UI/AddButtonIdentities";
```
Comment (Marchand-Nicolas) [inline pages/identities/[tokenId].tsx]: You can remove this import, it is not used

**Review by Marchand-Nicolas — APPROVED** [review]
Just little tweaks and we're good! The domain fetching works well, good job!

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Oops miss click sorry I mean't to request these changes @blessingbytes

**Review by Marchand-Nicolas — APPROVED** [review]
Lgtm! Good job
