### PR TITLE
fix: small UI issues

### LINKED ISSUE #883: TxConfirmationModal does not display correct transaction hash after disableRenewal method is called
Bug Description:
When the disableRenewal method is called, the TxConfirmationModal pops up, but the corresponding txHash is not set correctly. This results in the transaction hash not being displayed in the modal, causing confusion for the user.
Steps to Reproduce:
1. Trigger the disableRenewal method by clicking the "DISABLE SUBSCRIPTION" action.
2. Observe that the TxConfirmationModal pops up.
Notice that the transaction hash (txHash) is not displayed in the modal.
Expected Behavior:
The TxConfirmationModal should display the correct transaction hash (txHash) when the disableRenewal method is called.
Actual Behavior:
The TxConfirmationModal pops up without displaying the correct transaction hash (txHash).

### LINKED ISSUE #885: `term of use` ==> `terms of use`
image

### LINKED ISSUE #889: Shortened names are too short
Capture d’écran 2024-09-23 à 15 42 40

### PR DESCRIPTION
**Pull request by Marchand-Nicolas**
close: #885 
close: #883 
close: #889 

## Summary by CodeRabbit

- **Bug Fixes**
	- Updated the link label in the Desktop Navigation from "Term of use" to "Terms of use" for improved terminology consistency.
- **New Features**
	- Introduced a new function for advanced domain processing, enhancing how domain information is displayed in the Identities Gallery.
	- Implemented state management updates in the Identity Actions component to improve transaction handling for subscription renewals.
- **Tests**
	- Added a comprehensive test suite for the new domain processing function to ensure its reliability across various scenarios.

### CODE REVIEW

File: components/identities/actions/identityActions.tsx [hunk 1]
```diff
@@ -321,7 +324,11 @@ const IdentityActions: FunctionComponent<IdentityActionsProps> = ({
                       title="DISABLE SUBSCRIPTION"
                       description={nextAutoRenew}
                       icon={<div className={styles.renewalIconOff}>OFF</div>}
-                      onClick={() => disableRenewal()}
+                      onClick={() =>
+                        disableRenewal().then((res) =>
+                          setDisableRenewalTxHash(res.transaction_hash)
+                        )
```
Comment (fricoben) [inline components/identities/actions/identityActions.tsx]: Tu es sur que tu as besoin de ça ? le contrib qui a créé l'issue a aussi PR https://github.com/starknet-id/app.starknet.id/pull/884 je pense que sa PR fixe le tout

**Review by fricoben — CHANGES_REQUESTED** [review]
I think https://github.com/starknet-id/app.starknet.id/pull/884 fixed the hash issue (sorry I didn't close the issue after merge)

If it works no need to make change on the hash part !

**Review by fricoben — APPROVED** [review]
lgtm
