### PR TITLE
fix: manage external subdomains

### LINKED ISSUE #309: Verify that we manage all external domains
## Description

Today for external domains (.braavos.stark and .xplorer.stark) we can't transfer the names on the front-end even though the contract permits you to do it. 

We could add a transfer_name button to add this possibility, Argent and Braavos are using the same implementation for this contract right now so we would just need to have their contract address. 

Here is their implementation https://github.com/starknet-id/resolver_delegation

## ToDo or Verify

- [ ] It's indexed and you see them on `/indentities`
- [ ] The image that showsup is the right one (argent, braavos or bonfida)
- [ ] You can transfer it and set it as main domain

### PR DESCRIPTION
**Pull request by irisdv**
Close #309 

It's not possible to test the xplorer subdomains on sepolia. It seems there are no resolver contracts deployed on this network.

### CODE REVIEW

File: components/domains/externalDomainActions.tsx [hunk 1]
```diff
@@ -20,6 +23,8 @@ const ExternalDomainActions: FunctionComponent<ExternalDomainActionsProps> = ({
 }) => {
   const { address } = useAccount();
   const [isOwner, setIsOwner] = useState<boolean>(false);
+  const [isTransferFormOpen, setIsTransferFormOpen] = useState<boolean>(false);
+  const domainKind = getDomainKind(domain as string);
```
Comment (fricoben) [inline components/domains/externalDomainActions.tsx]: Why do you need to onforce `as string` ?

File: components/domains/externalDomainActions.tsx [hunk 2]
```diff
@@ -51,27 +56,67 @@ const ExternalDomainActions: FunctionComponent<ExternalDomainActionsProps> = ({
     set_address_to_domain();
   }
 
+  function getResolverContract(): string {
```
Comment (fricoben) [inline components/domains/externalDomainActions.tsx]: to put somehwere in utils and test. 

We'll reuse this more and more as we have more external subdomains being built. 

Maybe you can even add it to starknetid.js to make it available for everyone (up to you, if you find this relevant enough)

File: components/domains/externalDomainActions.tsx [hunk 3]
```diff
@@ -51,27 +56,67 @@ const ExternalDomainActions: FunctionComponent<ExternalDomainActionsProps> = ({
...
+    return domainKind === "xplorer"
+      ? (process.env.NEXT_PUBLIC_XPLORER_RESOLVER_CONTRACT as string)
+      : domainKind === "braavos"
+      ? (process.env.NEXT_PUBLIC_BRAAVOS_RESOLVER_CONTRACT as string)
+      : "";
+  }
+
+  function getResolverName(domainKind: DomainKind): string | undefined {
```
Comment (fricoben) [inline components/domains/externalDomainActions.tsx]: I would say same, utils and test.

File: components/domains/externalDomainTransferModal.tsx [hunk 4]
```diff
@@ -0,0 +1,168 @@
...
+    calls: callData,
+  });
+
+  useEffect(() => {
+    setCallData([
+      {
+        contractAddress: resolverContract,
+        entrypoint: "transfer_name",
+        calldata: [domainEncoded, targetAddress],
+      },
```
Comment (fricoben) [inline components/domains/externalDomainTransferModal.tsx]: Could we add this call data and the set as main domain for external domains to special file as we have for registerCalls.ts for example ?

File: components/domains/externalDomainTransferModal.tsx [hunk 5]
```diff
@@ -0,0 +1,168 @@
...
+  }, [addressInput, starknetIdNavigator]);
+
+  useEffect(() => {
+    if (!transferData?.transaction_hash) return;
+    addTransaction({
+      timestamp: Date.now(),
+      subtext: `${domain} transfered`,
+      type: NotificationType.TRANSACTION,
+      data: {
+        type: TransactionType.TRANSFER_IDENTITY,
```
Comment (fricoben) [inline components/domains/externalDomainTransferModal.tsx]: it's actually not transfer of an identity here don't you think ?

File: components/domains/externalDomainTransferModal.tsx [hunk 6]
```diff
@@ -0,0 +1,168 @@
...
+              <path
+                strokeLinecap="round"
+                strokeLinejoin="round"
+                strokeWidth="2"
+                d="M6 18L18 6M6 6l12 12"
+              ></path>
+            </svg>
+          </button>
+          <h2 className={styles.menu_title}>
+            Transfer your domain to a different wallet
```
Comment (fricoben) [inline components/domains/externalDomainTransferModal.tsx:131]: Quick question, here do we transfer the ownership and the target address at the same time ? Does the contract manage this as one address (owner = pointer) ?

File: components/domains/externalDomainTransferModal.tsx [hunk 7]
```diff
@@ -0,0 +1,168 @@
...
+          </h2>
+          {domainKind ? (
+            <p className="mt-5 text-center">
+              You can only transfer your subdomain to a {domainKind} wallet.
```
Comment (fricoben) [inline components/domains/externalDomainTransferModal.tsx]: Doesn't work for all of our cases (Xplorer wallet ? Sol wallet ?)

Capture d’écran 2024-04-26 à 11 10 12

File: components/domains/externalDomainTransferModal.tsx (hunk 5 above)
Comment (fricoben) [reply components/domains/externalDomainTransferModal.tsx]: Oh and I see you created the good type `TRANSFER_EXTERNAL_DOMAIN` so yeah it's a forget

**Review by fricoben — CHANGES_REQUESTED** [review]
A lot of small changes here and there :)

Looks good tho, I'll test E2E and my second review (.sol and .braavos)

File: components/domains/externalDomainTransferModal.tsx (hunk 5 above)
Comment (irisdv) [reply components/domains/externalDomainTransferModal.tsx]: Yes, I forgot to push that change

File: components/domains/externalDomainTransferModal.tsx (hunk 7 above)
Comment (irisdv) [reply components/domains/externalDomainTransferModal.tsx]: We can only transfer xplorer and braavos subdomains, but I'm not sure I understood your comment

Comment (irisdv) [reply components/domains/externalDomainTransferModal.tsx]: Ah you mean the return ? Actually the value is the result of the function `getResolverName`

File: components/domains/externalDomainActions.tsx (hunk 1 above)
Comment (irisdv) [reply components/domains/externalDomainActions.tsx]: no need actually

File: components/domains/externalDomainTransferModal.tsx (hunk 6 above)
Comment (irisdv) [reply components/domains/externalDomainTransferModal.tsx:131]: for external domains we just have a storage variable with the name > owner , so transferring it means both yes

File: components/domains/externalDomainTransferModal.tsx (hunk 7 above)
Comment (irisdv) [reply components/domains/externalDomainTransferModal.tsx]: I updated this to a new function called `getResolverCondition(domainKind: DomainKind)` in the transfer modal which returns the text to show, because it's really particular to this modal and shouldn't be needed elsewhere.

File: components/domains/externalDomainTransferModal.tsx (hunk 4 above)
Comment (fricoben) [reply components/domains/externalDomainTransferModal.tsx]: did you forget this comment ?

File: tests/utils/resolver.test.js [hunk 8]
```diff
@@ -0,0 +1,42 @@
+import { getResolverContract } from "../../utils/resolverService";
```
Comment (fricoben) [inline tests/utils/resolver.test.js]: `resolverService.test.js`

File: components/domains/externalDomainTransferModal.tsx [hunk 9]
```diff
@@ -0,0 +1,176 @@
...
+  function changeAddress(value: string): void {
+    setAddressInput(value);
+  }
+
+  function closeModal(): void {
+    setIsTxSent(false);
+    handleClose();
+  }
+
+  function getResolverCondition(domainKind: DomainKind): string | undefined {
```
Comment (fricoben) [inline components/domains/externalDomainTransferModal.tsx]: I added a comment here also to move that to utils + test it. Did you forget or didn't do it on purpose thinking it was better for it to stay here ?

**Review by fricoben — CHANGES_REQUESTED** [review]
Some last code review. 

I tested also on mainnet, I transferred fricoben.braavos.stark with `[this](https://starkscan.co/tx/0x45feadd5900e0a0f7d6369fb5e8966991c975838541f0b1481f7df06ba49bdf)` tx to testbraavos.stark. It seems the mainnet indexer doesn't catch the transfer event, so I still see my domain on fricoben.stark and don't see it on testbraavos.stark..

File: components/domains/externalDomainTransferModal.tsx (hunk 9 above)
Comment (irisdv) [reply components/domains/externalDomainTransferModal.tsx]: As I was saying in this comment, I updated the function : https://github.com/starknet-id/app.starknet.id/pull/748#discussion_r1581029618 
I can move it, but I'm not sure it will be useful elsewhere as it returns a text which is really specific to this component

File: components/domains/externalDomainTransferModal.tsx (hunk 4 above)
Comment (irisdv) [reply components/domains/externalDomainTransferModal.tsx]: Ah yes, I forgot about this.

**Review by fricoben — APPROVED** [review]
lgtm
