### PR TITLE
fix: wallet connect

### LINKED ISSUE #732: Add bitget wallet
https://starkgate.starknet.io/ added bitget wallet, I guess we can also add bitget wallet. 

We tried in the past and their infra didn't work but now, If it's on the bridge, it should be ready now ! 

Capture d’écran 2024-04-17 à 14 04 31

https://web3.bitget.com/en/docs/provider-api/starknet.html

### LINKED ISSUE #738: Wallet not reconnecting after refreshing page in sepolia
https://github.com/starknet-id/app.starknet.id/assets/55296770/6cbd1455-af30-4ae9-b768-581d93bfd546

Wallet not auto-connecting after refreshing page !

### PR DESCRIPTION
**Pull request by irisdv**
Close #738 
Close #732

### CODE REVIEW

**Review by fricoben — APPROVED** [review]
Wow works super good, congrats

File: utils/connectorWrapper.ts [hunk 1]
```diff
@@ -0,0 +1,153 @@
+import { constants } from "starknet";
```
Comment (fricoben) [inline utils/connectorWrapper.ts:1]: Every `utils` needs ti have his test file also :)

**Review by fricoben — CHANGES_REQUESTED** [review]
Just need to test unit and we're good

**Review by fricoben — APPROVED** [review]
lgtm
