### PR TITLE
### Fix: Update Domain Expiration Button Text (#1027)  - Changed the button text to display "Expired on (date)" when the domain has expired. - Retained the "Renew your domain" text if the domain is still active. - Updated the expiration logic in `registerCheckboxes.tsx`.  Closes #1027

### LINKED ISSUE #1027: Update the Domain Expiration feature - Change the text of the button
## Description 📹

Current design :
Image

New design :
Image

Figma file : https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=5274-23246&t=2SkxW4DSGWHqE5Q7-1

**Change the text of the 'renew your domain' button to 'Expired on (date)' when the domain has expired. Keep the current text when it has not yet expired.**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed with a mardown todo list]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by Godsmiracle001**
close: #1027 

## Summary by CodeRabbit

- **New Features**
  - Domain renewal actions now display dynamic status messages. Users will see a real-time indicator showing whether a domain has expired or is approaching its expiration date.

### CODE REVIEW

File: components/domains/registerCheckboxes.tsx [hunk 1]
```diff
@@ -6,83 +6,86 @@ import { CurrencyType } from "@/utils/constants";
...
-    </div>
-  );
+	const getHelperText = (): string => {
+		return `Enabling a subscription permits Starknet ID to  domain automatically every year for you! This approval gives us only the possibility to  domain once per year ${
+			maxPriceRange
+				? `(maximum ${weiToEth(maxPriceRange).toFixed(
+						3
+				  )} ${displayedCurrency}/year)`
+				: ""
+		} and we'll cover the transaction fee for you!`;
```
[the remark this answers is not in the document]
Comment (Godsmiracle001) [reply components/domains/registerCheckboxes.tsx]: Alright

**Comment by Godsmiracle001** [comment]
i am done with the changes, kindly review

**Review by Godsmiracle001 — COMMENTED** [review]
done

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
You need to add close: #issue-id in your PR's description.

Also, you can see it doesn't build.
Please use `npm run build` to debug

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
image
There are so much changes in your PR. Please remove that, only push the small piece of code that fixes the issue. + It doesn't work, I still see that it will expire in the past

**Comment by Godsmiracle001** [comment]
Changes done  @Marchand-Nicolas  pls review

File: components/domains/registerCheckboxes.tsx [hunk 2]
```diff
@@ -34,6 +34,14 @@ const RegisterCheckboxes: FunctionComponent<RegisterCheckboxes> = ({
   displayedCurrency = CurrencyType.ETH,
   maxPriceRange,
 }) => {
+  const expirationDate = new Date("2025-02-25"); // TODO: Fetch actual expiration date
```
Comment (Marchand-Nicolas) [inline components/domains/registerCheckboxes.tsx]: Do not hard code anything

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
It doesn't build. Use `npm run build` to debug.
Please make sure to check everything is good before pushing, because everytime I make a review, OD automatically reduces your reward

File: components/domains/registerCheckboxes.tsx (hunk 2 above)
Comment (Godsmiracle001) [reply components/domains/registerCheckboxes.tsx]: This has been fixed please review. Hardcode removed. i had issues with npm build but i resolved. @Marchand-Nicolas

**Review by Marchand-Nicolas — APPROVED** [review]
lgtm
