### PR TITLE
Fix: added a new cancel button when subscription is active #1099

### LINKED ISSUE #1099: New "subscription button" - Add a new cancel button when subscription is active
## Description 📹

Current :
Image

New design : 
Image

Figma : https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=6908-20924&t=XCt8XQUo4vZRtmIv-1

**Add a "Cancel Subscription" button to cancel the subscription.**

The purpose of this issue is to add a new "Cancel Subscription" button to the subscription component on the Starknet ID platform. Here are the details:

### Purpose of the Issue
Add a "Cancel Subscription" button to allow users to cancel their active subscription.

### Issue Details
- **Current State**: The cancellation button does not exist.
- **Proposed State**: A new "Cancel Subscription" button should be added according to the Figma design.
- **Design**: The new design is available on Figma (link provided in the issue description).

### Actions to Take
1. **Fork and Branch Creation**:
   - Fork the repository and create a new branch using the issue number.

2. **Implementation of Changes**:
   - Add the "Cancel Subscription" button according to the Figma design.
   - Ensure the button integrates properly with other components.

3. **Testing and Validation**:
   - Test modifications locally.
   - Verify that existing functionalities are not affected.

4. **Commit and Submission**:
   - Make a commit with a clear message describing the addition of the button.
   - Submit a pull request closing the issue.

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed with a mardown todo list]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by soomtochukwu**
Fix: add a new cancel button when subscription is active close: #1099 

## Summary by CodeRabbit

- **New Features**
  - The subscription card now displays the next payment date and includes a "CANCEL SUBSCRIPTION" button for active subscriptions.

- **Chores**
  - Updated a dependency version for improved consistency.
  - Added a development dependency for enhanced type support.

### CODE REVIEW

File: components/identities/actions/ActiveSubscriptionCard.tsx [hunk 1]
```diff
@@ -1,12 +1,35 @@
...
 import styles from "../../../styles/components/identityMenu.module.css";
+import { timestampToReadableDate } from "@/utils/dateService";
+import { Identity } from "@/utils/apiWrappers/identity";
+
+interface ActiveSubscriptionCardProps {
+  identity: Identity;
+}
+
+function ActiveSubscriptionCard({ identity }: ActiveSubscriptionCardProps) {
+  const cancelSubscription = () => {
```
Comment (Marchand-Nicolas) [inline components/identities/actions/ActiveSubscriptionCard.tsx]: No you need to use this instead:
```tsx
 const { sendAsync: disableRenewal, data: disableRenewalData } =
    useSendTransaction({
      calls: disableRenewalCalldata,
    });
```

All other necessary code and dependencies are here https://github.com/lfglabs-dev/app.starknet.id/blob/2ce90db5ce88e83c01a8f8fa8741692065bf642f/components/identities/actions/identityActions.tsx

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]

**Review by Marchand-Nicolas — APPROVED** [review]
Looks good, lgtm!
