### PR TITLE
fix: set as main domain

### LINKED ISSUE #716: User can not change his main domain
The user bought a domain while having a `.braavos.stark` as his main domain. 

### Case 1
1/ Buy tx https://starkscan.co/tx/0x05aa18c54db1eafdaeefc9d14bc7ef2424831af774d4a7e8a8a56bf8e18fa24c
2/ Clear legacy tx https://starkscan.co/tx/0x05530e6c154d322fa44d9a66c31b1bc81259fd54759a6510225bf174a59bfcbe

Ticket: https://discord.com/channels/1025416762835095674/1225738866615390229

### Case 2
Main domain on-chain is: 0x064e14ce64.stark
but https://api.starknet.id/domain_to_data?domain=daiphat.stark said it's daiphat.stark the main domain
Ticket: https://discord.com/channels/1025416762835095674/1226199651154395166

The two cases come from the same problem

### PR DESCRIPTION
**Pull request by irisdv**
Close #716 

Error originated from the check of `hasMainDomain` in the register component. The error occurred for user that had a domain starting with `0x`. I updated the check, and added an additional verification in the identity page to show the set as main domain button for users that had this bug.

### CODE REVIEW

File: components/identities/actions/identityActions.tsx [hunk 1]
```diff
@@ -66,6 +74,22 @@ const IdentityActions: FunctionComponent<IdentityActionsProps> = ({
...
 
+  // check if address_to_domain matches the domain of the identity
+  // if not, show set as main domain button
+  const { contract } = useNamingContract();
+  const { data: addrToDomainData, error: addrToDomainError } = useContractRead({
+    address: contract?.address as string,
+    abi: contract?.abi as Abi,
+    functionName: "address_to_domain",
+    args: [address as string],
+  });
```
Comment (fricoben) [inline components/identities/actions/identityActions.tsx]: Can't you use the Starknet React hook or starknetid.js here ?

File: components/domains/registerV2.tsx [hunk 2]
```diff
@@ -88,7 +88,9 @@ const RegisterV2: FunctionComponent<RegisterV2Props> = ({ domain, groups }) => {
   const { writeAsync: execute, data: registerData } = useContractWrite({
     calls: callData,
   });
-  const hasMainDomain = !useDisplayName(address ?? "", false).startsWith("0x");
+  const hasMainDomain = useDomainFromAddress(address ?? "").domain.endsWith(
+    ".stark"
+  );
```
Comment (fricoben) [inline components/domains/registerV2.tsx:93]: 😭

**Review by fricoben — CHANGES_REQUESTED** [review]
One question before merging + after merging, please deuplicate this PR to merge in sepolia

**Review by fricoben — APPROVED** [review]
Lgtm
